package config

func defaultSuites() Suites {
	return Suites{
		Common: []Pattern{
			{
				Name:     "unaligned-direct",
				Category: "unaligned",
				Params: map[string]string{
					"rw":              "randwrite",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "16",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "unaligned-buffered",
				Category: "unaligned",
				Params: map[string]string{
					"rw":              "randwrite",
					"ioengine":        "psync",
					"direct":          "0",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "unaligned-randread",
				Category: "unaligned",
				Params: map[string]string{
					"rw":              "randread",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "16",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "obj-boundary-3m",
				Category: "boundary",
				Params: map[string]string{
					"rw":               "randwrite",
					"bs":               "3m",
					"ioengine":         "libaio",
					"direct":           "1",
					"iodepth":          "16",
					"time_based":       "1",
					"verify":           "crc32c",
					"verify_backlog":   "64",
					"verify_fatal":     "1",
					"verify_dump":      "1",
					"random_generator": "lfsr",
					"group_reporting":  "1",
				},
			},
			{
				Name:     "obj-boundary-5m",
				Category: "boundary",
				Params: map[string]string{
					"rw":               "randwrite",
					"bs":               "5m",
					"ioengine":         "libaio",
					"direct":           "1",
					"iodepth":          "8",
					"time_based":       "1",
					"verify":           "crc32c",
					"verify_backlog":   "32",
					"verify_fatal":     "1",
					"random_generator": "lfsr",
					"group_reporting":  "1",
				},
			},
			{
				Name:     "mixed-bs-verify",
				Category: "integrity",
				Params: map[string]string{
					"rw":                "randrw",
					"rwmixread":         "50",
					"bssplit":           "4k/30:64k/30:512k/20:3m/20",
					"ioengine":          "libaio",
					"direct":            "1",
					"iodepth":           "16",
					"time_based":        "1",
					"verify":            "meta",
					"verify_backlog":    "128",
					"verify_fatal":      "1",
					"verify_dump":       "1",
					"serialize_overlap": "1",
					"group_reporting":   "1",
				},
			},
			{
				Name:     "data-integrity-4k",
				Category: "integrity",
				Params: map[string]string{
					"rw":               "randrw",
					"rwmixread":        "50",
					"bs":               "4k",
					"ioengine":         "libaio",
					"direct":           "1",
					"iodepth":          "32",
					"time_based":       "1",
					"verify":           "crc32c",
					"verify_backlog":   "256",
					"verify_fatal":     "1",
					"verify_dump":      "1",
					"random_generator": "lfsr",
					"group_reporting":  "1",
				},
			},
			{
				Name:     "seq-write-verify",
				Category: "integrity",
				Params: map[string]string{
					"rw":              "write",
					"bs":              "128k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "32",
					"time_based":      "1",
					"verify":          "crc32c",
					"verify_backlog":  "128",
					"verify_fatal":    "1",
					"verify_dump":     "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "high-iodepth-stress",
				Category: "stress",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "128",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "overwrite-frag-stress",
				Category: "stress",
				Size:     "64m",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "64",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "high-concurrency-randrw",
				Category: "stress",
				Params: map[string]string{
					"rw":              "randrw",
					"rwmixread":       "70",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "128",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "compress-pattern-stress",
				Category: "compression",
				Params: map[string]string{
					"rw":                         "randwrite",
					"bs":                         "128k",
					"ioengine":                   "libaio",
					"direct":                     "1",
					"iodepth":                    "16",
					"time_based":                 "1",
					"buffer_compress_percentage": "50",
					"verify":                     "crc32c",
					"verify_backlog":             "64",
					"verify_fatal":               "1",
					"group_reporting":            "1",
				},
			},
		},
		Filesystem: []Pattern{
			{
				Name:     "truncate-write",
				Category: "filesystem",
				Params: map[string]string{
					"rw":              "write",
					"bs":              "4k",
					"ioengine":        "psync",
					"direct":          "0",
					"fallocate":       "truncate",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "fsync-stress",
				Category: "filesystem",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "4k",
					"ioengine":        "psync",
					"direct":          "0",
					"fsync":           "1",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "fdatasync-mixed",
				Category: "filesystem",
				Params: map[string]string{
					"rw":              "randrw",
					"rwmixread":       "70",
					"bs":              "8k",
					"ioengine":        "psync",
					"direct":          "0",
					"fdatasync":       "1",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "append-write",
				Category: "filesystem",
				Params: map[string]string{
					"rw":              "write",
					"bs":              "64k",
					"ioengine":        "psync",
					"direct":          "0",
					"fallocate":       "none",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
		},
		Block: []Pattern{
			{
				Name:     "trim-write-interleave",
				Category: "block",
				Params: map[string]string{
					"rw":              "randtrimwrite",
					"bs":              "64k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "32",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "trim-stress",
				Category: "block",
				Params: map[string]string{
					"rw":              "randtrim",
					"bs":              "64k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "32",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "write-zeroes",
				Category: "block",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "64k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "16",
					"zero_buffers":    "1",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "sub-4k-rmw",
				Category: "block",
				Params: map[string]string{
					"rw":               "randwrite",
					"bs":               "512",
					"ioengine":         "libaio",
					"direct":           "1",
					"iodepth":          "32",
					"time_based":       "1",
					"verify":           "crc32c",
					"verify_backlog":   "256",
					"verify_fatal":     "1",
					"random_generator": "lfsr",
					"group_reporting":  "1",
				},
			},
		},
		CephFSRWX: []Pattern{
			{
				Name:     "rwx-concurrent-write",
				Category: "cephfs",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "16",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
			{
				Name:     "rwx-read-while-write",
				Category: "cephfs",
				Params: map[string]string{
					"rw":              "randread",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "16",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
		},
		Lifecycle: []Pattern{
			{
				Name:     "data-integrity-4k",
				Category: "lifecycle",
				Params: map[string]string{
					"rw":               "randrw",
					"rwmixread":        "50",
					"bs":               "4k",
					"ioengine":         "libaio",
					"direct":           "1",
					"iodepth":          "32",
					"time_based":       "1",
					"verify":           "crc32c",
					"verify_backlog":   "256",
					"verify_fatal":     "1",
					"verify_dump":      "1",
					"random_generator": "lfsr",
					"group_reporting":  "1",
				},
			},
			{
				Name:     "high-iodepth-stress",
				Category: "lifecycle",
				Params: map[string]string{
					"rw":              "randwrite",
					"bs":              "4k",
					"ioengine":        "libaio",
					"direct":          "1",
					"iodepth":         "128",
					"time_based":      "1",
					"group_reporting": "1",
				},
			},
		},
	}
}
